version: "3"
services:
  web:
    container_name: website
    build: nginx/.
    ports:
    - "80:80"
    depends_on: 
    - shiny
  shiny:
    container_name: shiny
    build: shiny/.
    ports:
    - "3838:3838"
